services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: api-gateway

    environment:
      NODE_ENV: production
      PORT: 3000

      # =========================
      # JWT SECURITY
      # =========================
      JWT_SECRET: ${JWT_SECRET}

      # =========================
      # FRONTEND CORS
      # =========================
      FRONTEND_URL: http://hrms-frontend:3000

      # =========================
      # RATE LIMITING
      # =========================
      RATE_LIMIT_WINDOW_MS: 15000
      RATE_LIMIT_MAX_REQUESTS: 100

    ports:
      - "3000:3000"

    networks:
      - hrms-network

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {if (r.statusCode !== 200) throw new Error(r.statusCode)})"]
      interval: 10s
      timeout: 5s
      retries: 5
    


networks:
  hrms-network:
    name: hrms-network
    external: true
    retries: 5
    start_period: 20s


