spring.application.name=performance-service
server.port=${SERVER_PORT:8086}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://hrms-postgres:5432/hrms_performance}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:hrms}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:hrms_pass}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}

logging.level.root=INFO
logging.level.com.hrms.performance=DEBUG

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
