apiVersion: v1
kind: Service
metadata:
  name: attendance-service
  namespace: hrms
  labels:
    app: attendance-service

spec:
  type: ClusterIP

  selector:
    app: attendance-service

  ports:
    - name: http
      port: 8085
      targetPort: 8085
      protocol: TCP
