version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: hrms-postgres
    restart: always
    environment:
      POSTGRES_DB: hrms_auth
      POSTGRES_USER: hrms
      POSTGRES_PASSWORD: hrms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: hrms-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  auth-service:
    build:
      context: ../../apps/auth-service
    container_name: auth-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hrms_auth
      SPRING_DATASOURCE_USERNAME: hrms
      SPRING_DATASOURCE_PASSWORD: hrms
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672

volumes:
  postgres_data: