package com.hrms.attendance_service.application.dto;

import com.hrms.attendance_service.common.enums.PlanningStatus;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

import java.time.LocalDate;

@Data
public class ShiftPlanningRequestDTO {
    
    @NotBlank
    private String employeeId;

    private String employeeName;

    private String departmentName;

    private String designationName;

    private String teamName;

    @NotNull
    private Long shiftId;

    @NotNull
    private LocalDate startDate;

    @NotNull
    private LocalDate endDate;

    private Boolean saturdayOff;

    private Boolean sundayOff;

    private Boolean flexibleShift;

    private Boolean autoGenerated;


    private PlanningStatus status;

    // ================= EXTRA =================

    private String note;
}
