apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: hrms
  labels:
    app: gateway-service
spec:
  type: LoadBalancer
  selector:
    app: gateway-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      protocol: TCP
  sessionAffinity: ClientIP
