apiVersion: v2
name: employee-service
description: A Helm chart for Employee Service in HRMS
type: application
version: 1.0.0
appVersion: "0.0.1-SNAPSHOT"
keywords:
  - employee
  - hrms
  - microservice
maintainers:
  - name: HRMS Team
home: https://github.com/hrms-sfe/atlashr
sources:
  - https://github.com/hrms-sfe/atlashr/apps/employee-service
