package com.hrms.attendance_service.domain.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;

import com.hrms.attendance_service.common.enums.PlanningStatus;

@Entity
@Table(
        name = "shift_plannings",
        uniqueConstraints = {
                @UniqueConstraint(
                        columnNames = {
                                "employeeId",
                                "startDate",
                                "endDate"
                        }
                )
        }
)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ShiftPlanning extends BaseEntity {

    // ================= EMPLOYEE =================

    @Column(nullable = false)
    private String employeeId;

    private String employeeName;

    private String departmentName;

    private String designationName;

    // ================= SHIFT =================

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "shift_id")
    private Shift shift;

    // ================= PERIOD =================

    @Column(nullable = false)
    private LocalDate startDate;

    @Column(nullable = false)
    private LocalDate endDate;

    // ================= DAYS OFF =================

    private Boolean saturdayOff;

    private Boolean sundayOff;

    // ================= ROSTER FEATURES =================

    // Team / Group
    private String teamName;

    // rotation cycle
    private Integer rotationWeek;

    // employee can switch shifts
    private Boolean flexibleShift;

    // priority scheduling
    private Integer priorityLevel;

    // generated automatically
    private Boolean autoGenerated;

    // temporary replacement
    private Boolean temporaryAssignment;

    // replacement employee
    private String replacementForEmployeeId;

    // ================= STATUS =================

    @Enumerated(EnumType.STRING)
    private PlanningStatus status;

    private String note;

    // ================= DEFAULTS =================

    @PrePersist
    public void prePersist() {

        if (this.saturdayOff == null)
            this.saturdayOff = false;

        if (this.sundayOff == null)
            this.sundayOff = true;

        if (this.status == null)
            this.status = PlanningStatus.ACTIVE;

        if (this.rotationWeek == null)
            this.rotationWeek = 1;

        if (this.flexibleShift == null)
            this.flexibleShift = false;

        if (this.priorityLevel == null)
            this.priorityLevel = 1;

        if (this.autoGenerated == null)
            this.autoGenerated = false;

        if (this.temporaryAssignment == null)
            this.temporaryAssignment = false;
    }

    // ================= HELPERS =================

    public boolean isActive() {

        return this.status == PlanningStatus.ACTIVE;
    }

    public boolean isInRange(LocalDate date) {

        return (date.isEqual(startDate)
                || date.isAfter(startDate))
                &&
                (date.isEqual(endDate)
                || date.isBefore(endDate));
    }

    public boolean isReplacement() {

        return Boolean.TRUE.equals(
                temporaryAssignment
        );
    }
}
