apiVersion: v1
kind: Secret
metadata:
  name: employee-service-secrets
  namespace: hrms
type: Opaque
stringData:
  db-username: "hrms"
  db-password: "hrms-secure-password"
  rabbitmq-username: "guest"
  rabbitmq-password: "guest"
