apiVersion: v1
kind: Secret
metadata:
  name: {{ include "attendance-service.fullname" . }}-secrets
  namespace: hrms
  labels:
    {{- include "attendance-service.labels" . | nindent 4 }}

type: Opaque

stringData:
  db-username: {{ .Values.secrets.dbUsername | quote }}
  db-password: {{ .Values.secrets.dbPassword | quote }}
  rabbitmq-username: {{ .Values.secrets.rabbitmqUsername | quote }}
  rabbitmq-password: {{ .Values.secrets.rabbitmqPassword | quote }}
  