apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "attendance-service.serviceAccountName" . }}
  namespace: hrms
  labels:
    {{- include "attendance-service.labels" . | nindent 4 }}
    